### PR TITLE
Javascript Validate Form (email lower case requirements)

### PR DESCRIPTION
**Pull request by gersonhiggins**
Update html form
Add css style for lowercase requirements message
Add Js LowerCase Requirement
Checkout Linters

### CODE REVIEW

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hi @gersonhiggins 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🔴 

You have submitted a project, that is missing the following:
- Your ` key features` section is not detailed. Using just "curriculum' is so vague and does not show the functionality added. Same for your `Future features`. Consider adding it 1 - 3
- As a pair activity, you need to add the contact your all contributors on the Author section
- Kindly personalize the license file. I'm seeing 2021 and no app mention
- You need to add a detailed way to clone and use your project under the `Setup, install, and usage` sections

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by gersonhiggins** [comment]
@Shedrack-Sunday are those requirements for this projects?

**Comment by Shedrack-Sunday** [comment]
> @Shedrack-Sunday are those requirements for this projects?

Hello @gersonhiggins, its a requirement for every project

**Review by LionRouge1 — COMMENTED** [review]
Hi @gersonhiggins, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a different PR for the same milestone, kindly use the same PR that you used for the first review to request for re-review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by GedeonTS — APPROVED** [review]
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @gersonhiggins ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

 

## Highlights :clap: :tophat: 
- No linter errors :+1: 
- The error message is displaying correctly :+1: 
## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
